const productos = [
  {
    id: 1,
    codigo: "TCL-001",
    nombre: "Teclado TKL 87 teclas",
    categoria: "teclados",
    precio: 49990,
    stock: 14,
    stockCritico: 3,
    switch: "Red (lineal)",
    descripcion: "Teclado mecánico TenKeyLess de 87 teclas, PCB hot-swap, cable USB-C desmontable.",
    imagen: "teclado-87.webp",
    destacado: true,
  },
  { 
    id: 2,
    codigo: "TCL-002",
    nombre: "Teclado Full Size 108 teclas",
    categoria: "teclados",
    precio: 54990,
    stock: 9,
    stockCritico: 3,
    switch: "Brown (táctil)",
    descripcion: "Layout completo con teclado numérico, retroiluminación RGB por tecla.",
    imagen: "teclado-fullsize.jpg",
    destacado: false,
  },
  {
    id: 3,
    codigo: "TCL-003",
    nombre: "Teclado 60% Compacto",
    categoria: "teclados",
    precio: 42990,
    stock: 20,
    stockCritico: 5,
    switch: "Blue (clicky)",
    descripcion: "El favorito para setups minimalistas: sin numpad, sin fila de función.",
    imagen: "teclado-60.jpg",
    destacado: false,
  },
  {
    id: 4,
    codigo: "TCL-004",
    nombre: "Kit teclado 65% (case + PCB + plate)",
    categoria: "kits",
    precio: 65000,
    stock: 11,
    stockCritico: 3,
    switch: "No incluye switches",
    descripcion: "Case de aluminio, PCB hot-swap y plate de policarbonato. Compatible 3 y 5 pines.",
    imagen: "kit-65-montaje.jpg",
    destacado: true,
  },
  {
    id: 5,
    codigo: "TCL-005",
    nombre: "Kit teclado 75% Gasket Mount",
    categoria: "kits",
    precio: 78000,
    stock: 6,
    stockCritico: 2,
    switch: "No incluye switches",
    descripcion: "Montaje gasket para un typing feel suave. Foam interno y estabilizadores lubricados.",
    imagen: "teclado-75-gasket.jpg",
    destacado: false,
  },
  {
    id: 6,
    codigo: "TCL-006",
    nombre: "Set Keycaps PBT Cherry Profile",
    categoria: "keycaps",
    precio: 24990,
    stock: 30,
    stockCritico: 8,
    switch: "N/A",
    descripcion: "108 teclas en perfil Cherry, doble disparo (dye-sub), compatibles con ANSI 60% a Full Size.",
    imagen: "keycaps-cherry.jpg",
    destacado: true,
  },
  {
    id: 7,
    codigo: "TCL-007",
    nombre: "Set Keycaps Primavera Pastel",
    categoria: "keycaps",
    precio: 27990,
    stock: 18,
    stockCritico: 5,
    switch: "N/A",
    descripcion: "Edición temática en tonos celestes, verdes y crema.",
    imagen: "keycaps-primavera.webp",
    destacado: true,
  },
  {
    id: 8,
    codigo: "TCL-008",
    nombre: "Pack 90 Switches Lineales",
    categoria: "switches",
    precio: 18500,
    stock: 40,
    stockCritico: 10,
    switch: "Lineal, 45g",
    descripcion: "Switches pre-lubricados, ideales para escritura silenciosa y gaming rápido.",
    imagen: "switch-lineal.webp",
    destacado: false,
  },
  {
    id: 9,
    codigo: "TCL-009",
    nombre: "Pack 90 Switches Táctiles",
    categoria: "switches",
    precio: 19500,
    stock: 25,
    stockCritico: 8,
    switch: "Táctil, 55g",
    descripcion: "El punto medio entre lineal y clicky: sientes el punto de actuación sin ruido.",
    imagen: "switch-tactil.png",
    destacado: false,
  },
  {
    id: 10,
    codigo: "TCL-010",
    nombre: "Reposamuñecas Ergonómico",
    categoria: "accesorios",
    precio: 12990,
    stock: 22,
    stockCritico: 6,
    switch: "N/A",
    descripcion: "Espuma viscoelástica forrada en cuero vegano, reduce tensión de muñeca.",
    imagen: "reposamunecas.avif",
    destacado: false,
  },
  {
    id: 11,
    codigo: "TCL-011",
    nombre: "Cable USB-C Coiled Celeste",
    categoria: "accesorios",
    precio: 9990,
    stock: 2,
    stockCritico: 3,
    switch: "N/A",
    descripcion: "Cable en espiral de 1.8m, conector aviador desmontable, en celeste de marca.",
    imagen: "cable-usb-celeste.png",
    destacado: false,
  },
  {
    id: 12,
    codigo: "TCL-012",
    nombre: "Herramienta Extractora de Keycaps",
    categoria: "accesorios",
    precio: 4990,
    stock: 50,
    stockCritico: 10,
    switch: "N/A",
    descripcion: "Extractor de alambre que no raya tus keycaps. Incluye extractor de switches.",
    imagen: "extractor-keycap.jpg",
    destacado: false,
  },
];
