const productos = [
  {
    id: 1,
    nombre: "Teclado TKL 87 teclas",
    categoria: "teclados",
    precio: 49990,
    stock: 14,
    stockCritico: 3,
    switch: "Red (lineal)",
    descripcion: "Teclado mecánico TenKeyLess de 87 teclas, PCB hot-swap, cable USB-C desmontable.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=TKL+87",
    destacado: true,
  },
  {
    id: 2,
    nombre: "Teclado Full Size 108 teclas",
    categoria: "teclados",
    precio: 54990,
    stock: 9,
    stockCritico: 3,
    switch: "Brown (táctil)",
    descripcion: "Layout completo con teclado numérico, retroiluminación RGB por tecla.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Full+Size",
    destacado: false,
  },
  {
    id: 3,
    nombre: "Teclado 60% Compacto",
    categoria: "teclados",
    precio: 42990,
    stock: 20,
    stockCritico: 5,
    switch: "Blue (clicky)",
    descripcion: "El favorito para setups minimalistas: sin numpad, sin fila de función.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=60%25",
    destacado: false,
  },
  {
    id: 4,
    nombre: "Kit teclado 65% (case + PCB + plate)",
    categoria: "kits",
    precio: 65000,
    stock: 11,
    stockCritico: 3,
    switch: "No incluye switches",
    descripcion: "Case de aluminio, PCB hot-swap y plate de policarbonato. Compatible 3 y 5 pines.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Kit+65%25",
    destacado: true,
  },
  {
    id: 5,
    nombre: "Kit teclado 75% Gasket Mount",
    categoria: "kits",
    precio: 78000,
    stock: 6,
    stockCritico: 2,
    switch: "No incluye switches",
    descripcion: "Montaje gasket para un typing feel suave. Foam interno y estabilizadores lubricados.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Kit+75%25",
    destacado: false,
  },
  {
    id: 6,
    nombre: "Set Keycaps PBT Cherry Profile",
    categoria: "keycaps",
    precio: 24990,
    stock: 30,
    stockCritico: 8,
    switch: "N/A",
    descripcion: "108 teclas en perfil Cherry, doble disparo (dye-sub), compatibles con ANSI 60% a Full Size.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Keycaps+PBT",
    destacado: true,
  },
  {
    id: 7,
    nombre: "Set Keycaps Primavera Pastel",
    categoria: "keycaps",
    precio: 27990,
    stock: 18,
    stockCritico: 5,
    switch: "N/A",
    descripcion: "Edición temática en tonos celestes, verdes y crema.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Keycaps+Primavera",
    destacado: true,
  },
  {
    id: 8,
    nombre: "Pack 90 Switches Lineales",
    categoria: "switches",
    precio: 18500,
    stock: 40,
    stockCritico: 10,
    switch: "Lineal, 45g",
    descripcion: "Switches pre-lubricados, ideales para escritura silenciosa y gaming rápido.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Switches+Lineales",
    destacado: false,
  },
  {
    id: 9,
    nombre: "Pack 90 Switches Táctiles",
    categoria: "switches",
    precio: 19500,
    stock: 25,
    stockCritico: 8,
    switch: "Táctil, 55g",
    descripcion: "El punto medio entre lineal y clicky: sientes el punto de actuación sin ruido.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Switches+Tactiles",
    destacado: false,
  },
  {
    id: 10,
    nombre: "Reposamuñecas Ergonómico",
    categoria: "accesorios",
    precio: 12990,
    stock: 22,
    stockCritico: 6,
    switch: "N/A",
    descripcion: "Espuma viscoelástica forrada en cuero vegano, reduce tensión de muñeca.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Reposamuñecas",
    destacado: false,
  },
  {
    id: 11,
    nombre: "Cable USB-C Coiled Celeste",
    categoria: "accesorios",
    precio: 9990,
    stock: 2,
    stockCritico: 3,
    switch: "N/A",
    descripcion: "Cable en espiral de 1.8m, conector aviador desmontable, en celeste de marca.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Cable+Coiled",
    destacado: false,
  },
  {
    id: 12,
    nombre: "Herramienta Extractora de Keycaps",
    categoria: "accesorios",
    precio: 4990,
    stock: 50,
    stockCritico: 10,
    switch: "N/A",
    descripcion: "Extractor de alambre que no raya tus keycaps. Incluye extractor de switches.",
    imagen: "https://placehold.co/500x400/4cc9f0/ffffff?text=Extractor",
    destacado: false,
  },
];