const usuariosSemilla = [
  {
    id: 1,
    run: "190110229",
    nombre: "Diego",
    apellidos: "Lobos Ortiz",
    correo: "dlobos.or@gmail.com",
    fechaNacimiento: "",
    tipoUsuario: "Administrador",
    region: "Región Metropolitana de Santiago",
    comuna: "Santiago",
    direccion: "Av. Principal 123",
  },
  {
    id: 2,
    run: "156789034",
    nombre: "Camila",
    apellidos: "Reyes Pérez",
    correo: "camila.reyes@duoc.cl",
    fechaNacimiento: "",
    tipoUsuario: "Vendedor",
    region: "Región de Valparaíso",
    comuna: "Viña del Mar",
    direccion: "Calle Los Álamos 456",
  },
  {
    id: 3,
    run: "178234567",
    nombre: "Javier",
    apellidos: "Muñoz Soto",
    correo: "javier.munoz@gmail.com",
    fechaNacimiento: "",
    tipoUsuario: "Cliente",
    region: "Región del Biobío",
    comuna: "Concepción",
    direccion: "Pasaje Las Rosas 789",
  },
];